
// ============================================
// SAAS / MASTER BACKOFFICE TYPES
// ============================================

export enum SaaSLeadStage {
    NEW = 'New',
    QUALIFIED = 'Qualified',
    DEMO_SCHEDULED = 'Demo Scheduled',
    TRIAL_STARTED = 'Trial Started',
    CLOSED_WON = 'Closed Won',
    CLOSED_LOST = 'Closed Lost'
}

export enum SaaSPlan {
    START = 'Start',
    GROWTH = 'Growth',
    EXPERTS = 'Experts',
    EMPIRE = 'Empire'
}

export interface SaaSLead {
    id: string;
    name: string; // Nome do lead (pessoa)
    clinicName: string; // Nome da clínica (empresa)
    legalName?: string; // Razão Social
    email: string;
    phone: string;
    stage: SaaSLeadStage;
    planInterest: SaaSPlan; // Qual plano demonstrou interesse
    source: 'landing_page' | 'referral' | 'outbound' | 'other';
    status: 'active' | 'archived'; // Se já foi processado ou não
    notes?: string;
    estimatedValue?: number; // Preço do plano estimado
    nextAction?: string; // "Ligar amanhã", "Enviar contrato"
    cnpj?: string; // For invoice
    address?: string; // Logradouro
    number?: string;
    complement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    paymentMethod?: 'boleto' | 'pix' | 'credit_card';
    recurrence?: 'monthly' | 'annual';
    trialStartDate?: string;
    zipCode?: string;
    tasks?: SaaSTask[];
    tags?: string[]; // Etiquetas para segmentação (ex: "Calculadora", "Ebook")
    metadata?: Record<string, any>; // Dados ricos (ex: Resultado da Calculadora)
    attachments?: string[]; // URLs de arquivos gerados/enviados
    createdAt: string;
    updatedAt: string;
}

export type SaaSTaskType = 'call' | 'meeting' | 'email' | 'reminder' | 'demo';

export interface SaaSTask {
    id: string;
    leadId: string;
    title: string;
    type: SaaSTaskType;
    dueDate: string;
    isCompleted: boolean;
}

export interface SaaSSubscriber {
    id: string; // org_id
    clinicName: string;
    adminName: string;
    adminEmail: string;
    adminPhone: string;
    plan: SaaSPlan;
    status: 'active' | 'delinquent' | 'cancelled' | 'trial';
    mrr: number; // Monthly Recurring Revenue
    joinedAt: string; // Data de início
    nextBillingDate: string;
    usersCount: number; // Quantos usuários cadastrados
    smsBalance: number; // Saldo de mensagens
    asaasCustomerId?: string; // ID do cliente no Asaas (cus_...)
    asaasSubscriptionId?: string; // ID da assinatura no Asaas (sub_...)
}

// ============================================
// NEW PIPELINES TYPES
// ============================================

// 1. Implementation Pipeline
export enum ImplementationStage {
    NEW_SUBSCRIBER = 'New Subscriber',
    DEMO_SCHEDULED = 'Demo Scheduled',
    IN_TRAINING = 'In Training',
    FINISHED = 'Finished'
}

export interface ImplementationProject {
    id: string;
    subscriberId: string; // Links to SaaSSubscriber (org_id)
    clinicName: string;
    stage: ImplementationStage;
    startDate: string;
    deadlineDate: string; // 30 days from start
    modulesChecked: string[]; // List of modules trained (e.g., 'financial', 'calendar')
    status: 'on_track' | 'at_risk' | 'delayed' | 'completed';
    notes?: string;
    tasks?: SaaSTask[]; // Tasks specific to implementation
}

// 2. Support Pipeline
export enum SupportTicketStatus {
    OPEN = 'Open',
    IN_PROGRESS = 'In Progress',
    WAITING_CLIENT = 'Waiting Client',
    RESOLVED = 'Resolved',
    CLOSED = 'Closed'
}

export enum SupportTicketPriority {
    LOW = 'Low',
    MEDIUM = 'Medium',
    HIGH = 'High',
    CRITICAL = 'Critical'
}

export interface SupportTicket {
    id: string;
    ticketNumber: string; // #1234
    subscriberId: string;
    clinicName: string;
    title: string;
    description: string;
    category: 'bug' | 'question' | 'access' | 'other';
    priority: SupportTicketPriority;
    status: SupportTicketStatus;
    aiSummary?: string; // Summary generated by AI
    createdAt: string;
    updatedAt: string;
    assignedTo?: string; // Agent name
    messages?: { author: 'agent' | 'client' | 'system', content: string, timestamp: string }[];
}

// 3. Improvements & Suggestions
export enum FeatureRequestImpact {
    LOW = 'Low', // Nice to have
    MEDIUM = 'Medium', // Important
    HIGH = 'High', // Urgent need
    CRITICAL = 'Critical' // Deal breaker
}

export enum FeatureRequestStatus {
    NEW = 'New',
    UNDER_REVIEW = 'Under Review',
    PLANNED = 'Planned',
    IN_DEVELOPMENT = 'In Development',
    RELEASED = 'Released',
    REJECTED = 'Rejected'
}

export interface FeatureRequest {
    id: string;
    subscriberId: string;
    clinicName: string;
    module: string; // 'financial', 'calendar', 'marketing', etc.
    title: string;
    description: string;
    impact: FeatureRequestImpact;
    status: FeatureRequestStatus;
    votes: number; // For internal prioritization
    createdAt: string;
}
